project_id = "aktkjuynewgneyogwlvw"
[functions.create-and-insert-spare-parts]
enabled = true
verify_jwt = true
import_map = "./functions/create-and-insert-spare-parts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-and-insert-spare-parts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-and-insert-spare-parts/*.html" ]
